/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.application;
@SuppressWarnings("all")
/** SNTP (Simple Network Time Protocol) synchronizes with a single server once, NTP (Network Time Protocol) may synchronize with multiple servers and derive some continuous measures. */
@org.apache.avro.specific.AvroGenerated
public enum ExternalTimeProtocol {
  SNTP, NTP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ExternalTimeProtocol\",\"namespace\":\"org.radarcns.application\",\"doc\":\"SNTP (Simple Network Time Protocol) synchronizes with a single server once, NTP (Network Time Protocol) may synchronize with multiple servers and derive some continuous measures.\",\"symbols\":[\"SNTP\",\"NTP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
